Refactoring/Gestion_BU/Gestion_BU/Entities/Etudiant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Gestion_BU.Entities
{
    public class Etudiant
    {
        public string AdresseEmail { get; private set; }
        public int UniversiteId { get; private set; }
        public int NbTelechargementMaximum { get; set; }
        public int NbLivreTelecharges { get; set; }

        public Etudiant(string emailAddress, int universityId)
        {
            AdresseEmail = emailAddress;
            UniversiteId = universityId;
        }
    }
}

Refactoring/Gestion_BU/Gestion_BU/Entities/Forfait.cs
namespace Gestion_BU.Entities
{
    public enum Forfait
    {
        Standard = 1,
        Premium = 2,
    }
}

Refactoring/Gestion_BU/Gestion_BU/Entities/Universite.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Gestion_BU.Entities
{
    public class Universite
    {
        public int Id { get;  set; }
        public string Name { get;  set; }
        public Forfait Forfait { get;  set; }
    }
}

Refactoring/Gestion_BU/Gestion_BU/ViewModels/ErrorViewModel.cs
namespace Gestion_BU.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Refactoring/Gestion_BU/Gestion_BU/ViewModels/EtudiantViewModel.cs
using Gestion_BU.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Gestion_BU.ViewModels
{
    public class EtudiantViewModel
    {
        public EtudiantViewModel()
        {

        }
        public EtudiantViewModel(List<Universite> universities)
        {
            Universites = new SelectList(universities, "Id", "Name");
        }

        [Required, DataType(DataType.EmailAddress)]
        public string? Email { get; set; }

        [DisplayName("Université")]
        public int UniversiteId { get; set; }

        public SelectList Universites { get; set; }
    }
}

Refactoring/Gestion_BU/Gestion_BU/ViewModels/UniversiteViewModel.cs
using Gestion_BU.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Gestion_BU.ViewModels
{
    public class UniversiteViewModel
    {
        public UniversiteViewModel()
        {

        }
        public int Id { get; set; }
        public string Nom { get; set; }

        public string NomForfait { get; set; }
    }
}

Refactoring/Gestion_BU/Gestion_BU/Controllers/EtudiantController.cs
using Gestion_BU.Repositories;
using Gestion_BU.Services;
using Gestion_BU.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Gestion_BU.Controllers
{
    public class EtudiantController : Controller
    {
        private readonly RegistreService _registreService;
        private readonly UniversiteRepository _universiteRepository;

        private readonly EdutiantRepository _etudiantRepository;

        public EtudiantController(RegistreService registreService, UniversiteRepository universityRepository, EdutiantRepository edutiantRepository)
        {
            _registreService = registreService;
            _universiteRepository = universityRepository;
            _etudiantRepository = edutiantRepository;
        }

        public IActionResult Index()
        {
            var etudiants = _etudiantRepository.GetEtudiants();
            var etudiantsVm = new List<EtudiantViewModel>();
            foreach (var item in etudiants)
            {
                etudiantsVm.Add(new EtudiantViewModel()
                {
                    Email = item.AdresseEmail,
                    UniversiteId = item.UniversiteId,
                });
            }
            return View(etudiantsVm);
        }


        public IActionResult Add()
        {
            var vm = new EtudiantViewModel(_universiteRepository.GetAll());
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(EtudiantViewModel viewModel)
        {
            _registreService.AjouterEtudiant(viewModel.Email, viewModel.UniversiteId);
            return RedirectToAction("Index");
        }
    }
}

Refactoring/Gestion_BU/Gestion_BU/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Gestion_BU.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
     }
}

Refactoring/Gestion_BU/Gestion_BU/Controllers/UniversiteController.cs
using Gestion_BU.Repositories;
using Gestion_BU.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Gestion_BU.Controllers
{
    public class UniversiteController : Controller
    {
        private readonly UniversiteRepository _universityRepository;

 

        public UniversiteController( UniversiteRepository universityRepository )
        {
            _universityRepository = universityRepository;
        }

        public IActionResult Index()
        {
            var universities = _universityRepository.GetAll();
            var universitesVm = new List<UniversiteViewModel>();
            foreach (var item in universities)
            {
                universitesVm.Add(new UniversiteViewModel()
                {
                    Id = item.Id,
                    Nom = item.Name,
                    NomForfait = item.Forfait.ToString()
                });
            }
            return View(universitesVm);
        }


    }
}

Refactoring/Gestion_BU/Gestion_BU/Views/Etudiant/Add.cshtml
@model Gestion_BU.ViewModels.EtudiantViewModel

@{
    ViewData["Title"] = "Ajouter un étudiant au registre";
}

<h1>Ajouter un étudiant au registre</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UniversiteId" class="control-label"></label>
                <select asp-for="UniversiteId" class="form-control" asp-items="Model.Universites" ></select>
                <span asp-validation-for="UniversiteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Refactoring/Gestion_BU/Gestion_BU/Views/Etudiant/Index.cshtml
@model IEnumerable<Gestion_BU.ViewModels.EtudiantViewModel>

@{
    ViewData["Title"] = "List";
}

<h1>Liste des etudiants</h1>

<p>
    <a asp-action="Add">Ajouter</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UniversiteId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UniversiteId)
            </td>
        </tr>
}
    </tbody>
</table>

Refactoring/Gestion_BU/Gestion_BU/Views/Home/Index.cshtml
@model IEnumerable<Gestion_BU.ViewModels.EtudiantViewModel>

@{
    ViewData["Title"] = "List";
}
<style>

</style>

<h1>GestionBU SAS - Gestion des bibliothèques universitaire</h1>

<p>
    GestionBU est une bibliothèque en ligne qui vend ses services aux universités.
    Les universités l'utilisent en mode SaaS (en tant que plateforme) pour permettre à leurs étudiants de lire/télécharger des livres électroniques.
</p>
<br />
<p>
    Les utilisateurs de cette application (les étudiants) peuvent se connecter avec les informations d'identification fournies par leur université et télécharger des livres électroniques.
    Il y a une limite mensuelle d'e-books qu'un étudiant peut télécharger.
    Cette allocation mensuelle est basée sur le forfait acheté par l'université à laquelle appartient l'étudiant.
</p>
<p>
    Pour qu'un étudiant puisse avoir accès aux livres grâce au forfait offert par son université, l'édutiant doit être inscrit dans un registre. Le registre relie un étudiant à une université.
</p>

<button type="button" class="collapsible">Aide Memoire</button>
<div class="content">
    <ul>
        <li>S : Single Responsibility Principle (SRP) <br /> Une classe ne doit avoir qu'une seule et unique responsabilité.</li>
        <li>O : Open/Closed Principle <br />Les entités doivent être ouvertes à l'extension et fermées à la modification.</li>
        <li>L : Liskov’s Substitution Principle (LSP) <br /> Les objets dans un programme doivent être remplaçables par des instances de leur sous-type sans pour autant altérer le bon fonctionnement du programme.</li>
        <li>I : Interface Segregation Principle (ISP) <br /> Aucun client ne devrait être forcé d'implémenter des méthodes / fonctions qu'il n'utilise pas.</li>
        <li><strong>D : Dependency Inversion Principle (DIP) </strong><br /> Une classe doit dépendre de son abstraction, pas de son implémentation.</li>
    </ul>
</div>

<h2 style="margin-top:10px">Exercices</h2>

<strong>Etape 1</strong>
<p>1. En utilisant vos connaissances et les principes S.O.L.I.D, refactorisez l'application afin de permettre une meilleure séparation des couches,et une meilleure testabilité/lisibilité
<br/> L'esentiel de vos changements s'effectueront au sein de la classe RegistreService.</p>


<strong>Etape 2</strong>
<p>2. Nous avons besoin d'ajouter la fonctionnalité suivante:
<p style="font-style:italic;">Permettre à travers l'application de gestion, d'augmenter le nombre de téléchargement que peut faire un étudiant en fonction du forfait acheté par l'université.</p></p>
<p>Si le forfait souscrit par l'université de l'étudiant est <br />
    <strong>Standard</strong>: le nombre de téléchargement autorisé augmente de 5.<br />
    <strong>Premuim</strong>:  le nombre de téléchargement autorisé augmente de 10.<br /><br />
    <strong>Consigne</strong>: Proposez une implémentation qui respecte ces nouvelles contraintes, tout en respectant au maximum les principes S.O.L.I.D
</p>

<strong>Etape 3</strong>
<p>Il existe maintenant une nouvelle exigence pour ajouter un nouveau type de forfait , "Illimité". Les étudiants des universités qui ont acheté ce forfait n'ont pas de limite d'allocation mensuelle.
    <br /> Cette nouvelle contrainte vient probablement  à l'encontre de certaines modifications effectués lors de l'étape 2, faîtes les changements en conséquence.
</p>
<strong>Consigne</strong>: Proposez une implémentation qui respecte ces nouvelles contraintes, tout en respectant au maximum les principes S.O.L.I.D

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }
</script>

Refactoring/Gestion_BU/Gestion_BU/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionBU</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestionBU.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestionBU</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Etudiant" asp-action="Index">Etudiants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Universite" asp-action="Index">Universités</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GestionBU - <a asp-area="" asp-controller="Etudiant" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Refactoring/Gestion_BU/Gestion_BU/Views/Universite/Index.cshtml
@model IEnumerable<Gestion_BU.ViewModels.UniversiteViewModel>

@{
    ViewData["Title"] = "Liste des universités";
}

<h1>Liste des universités</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomForfait)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomForfait)
            </td>
        </tr>
}
    </tbody>
</table>